# Generated by Django 4.2.5 on 2023-10-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='audio_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
